apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pofms1t50-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pofms1t50-nodejs 
  name: pofms1t50-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pofms1t50-nodejs 
